## Este notebook funciona con los datos v6 (7 variables) y con el HT de Irene


In [45]:
import sys
import requests
import inspect
import pandas as pd
import random
import csv
import numpy as np
import os

#sys.path.append("3_Copies/code_source")
from methods import HoeffdingTree
from sklearn.metrics import confusion_matrix
print ('\n'.join(sys.path))

/Users/irene/Documents/Projects/dual/scripts/methods/
/Users/irene/Documents/Projects/dual/scripts/methods/
/Users/irene/Documents/Projects/dual/scripts/methods/
/Users/irene/Documents/Projects/dual/scripts/methods/
/opt/anaconda3/envs/skmultiflow_dev/lib/python36.zip
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/lib-dynload

/Users/MiguelNunez/.local/lib/python3.6/site-packages
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/aeosa
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/IPython/extensions
/Users/MiguelNunez/.ipython


## Data generation

In [46]:
dataset_feature_names=[     'amount_usd',      
                            'client_age',
                            'client_gender',     # 1 Male other female
                            'debit_type',        # Credit 1or debit 0 card
                            'agency_region',     
                            'merchant_departement',
                            'coicop',
                            'social_class']

df = pd.read_csv('../data_output/export_dataframe_0v6.csv',header=None,names=dataset_feature_names)
df.head()

amount_usd  client_age  client_gender  debit_type  agency_region  \
0    0.002222    0.345794              0           1              9   
1    0.000241    0.364486              1           1              5   
2    0.000454    0.317757              0           1              9   
3    0.000244    0.327103              0           1              8   
4    0.001783    0.242991              0           1             11   

   merchant_departement  coicop  social_class  
0                    15       1             0  
1                    15       1             0  
2                    15       1             0  
3                    15       1             0  
4                    11      12             0

## Generate adnostic uniform sample

In [47]:
y=np.asarray(df['social_class'])
X=np.asarray(df.iloc[:,0:-1])

In [48]:
cfiers = [HoeffdingTree(splitter="mean",max_samples=10000),HoeffdingTree(splitter="median",max_samples=10000)]

In [49]:
cfiers[0].fit(X,y)

HoeffdingTree(max_depth=None, max_samples=10000, min_samples_leaf=1,
              min_samples_split=100, min_samples_split_lower=2,
              random_state=None, splitter='mean')

In [50]:
yPred0 = cfiers[0].predict(X)
print (yPred0)

[0 0 0 ... 0 0 0]


In [51]:
cfiers[1].fit(X,y)

HoeffdingTree(max_depth=None, max_samples=10000, min_samples_leaf=1,
              min_samples_split=100, min_samples_split_lower=2,
              random_state=None, splitter='median')

In [52]:
cfiers[1].fit(X,y)
yPred1 = cfiers[1].predict(X)
print (yPred1)

[0 0 0 ... 0 0 0]


In [53]:
np.unique(yPred0,return_counts=True)

(array([0, 1]), array([946806,  53194]))

In [54]:
np.unique(yPred1,return_counts=True)

(array([0, 1]), array([947457,  52543]))

## Copy