# HoeffdingTree using scikit-multiflow

In [1]:
from skmultiflow.trees import HoeffdingTree
from skmultiflow.trees.hoeffding_adaptive_tree import HAT
from skmultiflow.data.file_stream import FileStream
from skmultiflow.evaluation.evaluate_prequential import EvaluatePrequential
import numpy as np

In [2]:
def compute_y_weight(y):
    aux = np.unique(y,return_counts=True)
    nb_classes = len(aux[0])
    list_classes = aux[0]
    count_classes = aux[1]
    sum_classes =  float(np.sum(count_classes))
    weight_classes = count_classes/sum_classes
    y_weights = y.copy()
    
    i = 0
    while i < nb_classes:
        
        class_i = list_classes[i]
        y_weights = np.where(y_weights==float(class_i), weight_classes[i], y_weights) 
        i += 1
    return y_weights

In [3]:
pCat_features_idx = list(range(2,45))

# Setup the File Stream
stream = FileStream("../data_output/export_dataframe_0v4.csv", -1, 1,  pCat_features_idx)
#stream = FileStream("../data_output/balanced.csv", -1, 1,  pCat_features_idx)
stream.prepare_for_use()
#X, y = stream.next_sample(10000)
#y_weights = compute_y_weight(y)

cfiers = [HoeffdingTree(nominal_attributes=[0,1],split_confidence=1e-10), 
          HAT(nominal_attributes=[0,1],split_confidence=1e-10)
         ]
#classifier.partial_fit(X,y,[0,1],y_weights )
evaluator = EvaluatePrequential(pretrain_size=10000, max_samples=1000000, batch_size=100, n_wait=200, max_time=10000,
                                 output_file='summary_ht_balanced.txt', show_plot=False, 
                                metrics=['accuracy','true_vs_predicted'#,
                                         #'precision','recall','f1',
                                         #'running_time','model_size'
                                        ])

models = evaluator.evaluate(stream=stream, model=cfiers, model_names=['HT', 'HAT']);
#0.8499

/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg/skmultiflow/data/base_stream.py:193: FutureWarning: 'prepare_for_use' has been deprecated in v0.5.0 and will be removed in v0.7.0.
New instances of the Stream class are now ready to use after instantiation.
  category=FutureWarning)
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg/skmultiflow/trees/hoeffding_tree.py:34: FutureWarning: 'HoeffdingTree' has been renamed to 'HoeffdingTreeClassifier' in v0.5.0.
The old name will be removed in v0.7.0
  "The old name will be removed in v0.7.0", category=FutureWarning)
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg/skmultiflow/trees/hoeffding_adaptive_tree.py:17: FutureWarning: 'HAT' has been renamed to 'HoeffdingAdaptiveTreeClassifier' in v0.5.0.
The old name will be removed in v0.7.0
 

Prequential Evaluation
Evaluating 1 target(s).
Pre-training on 10000 sample(s).
Evaluating...

Processed samples: 338100
Mean performance:
HT - Accuracy     : 0.8202
HAT - Accuracy     : 0.8455


In [4]:
pCat_features_idx = list(range(2,45))

# Setup the File Stream
stream = FileStream("../data_output/export_dataframe_0v4.csv", -1, 1,  pCat_features_idx)
#stream = FileStream("../data_output/balanced.csv", -1, 1,  pCat_features_idx)
stream.prepare_for_use()
X, y = stream.next_sample(10000)
y_weights = compute_y_weight(y)

cfiers = [HoeffdingTree(nominal_attributes=[0,1],split_confidence=1e-10), 
          HAT(nominal_attributes=[0,1],split_confidence=1e-10)
         ]
cfiers[0].partial_fit(X,y,[0,1],y_weights )
cfiers[1].partial_fit(X,y,[0,1],y_weights )

evaluator = EvaluatePrequential(pretrain_size=10000, max_samples=1000000, batch_size=100, n_wait=200, max_time=1000,
                                 output_file='summary_ht_balanced_partialfit.txt', show_plot=False, 
                                metrics=['accuracy','true_vs_predicted'#,
                                         #'precision','recall','f1',
                                         #'running_time','model_size'
                                        ])
models = evaluator.evaluate(stream=stream, model=cfiers, model_names=['HT', 'HAT']);
#0.8499

/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg/skmultiflow/data/base_stream.py:193: FutureWarning: 'prepare_for_use' has been deprecated in v0.5.0 and will be removed in v0.7.0.
New instances of the Stream class are now ready to use after instantiation.
  category=FutureWarning)
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg/skmultiflow/trees/hoeffding_tree.py:34: FutureWarning: 'HoeffdingTree' has been renamed to 'HoeffdingTreeClassifier' in v0.5.0.
The old name will be removed in v0.7.0
  "The old name will be removed in v0.7.0", category=FutureWarning)
/opt/anaconda3/envs/skmultiflow_dev/lib/python3.6/site-packages/scikit_multiflow-0.5.dev0-py3.6-macosx-10.9-x86_64.egg/skmultiflow/trees/hoeffding_adaptive_tree.py:17: FutureWarning: 'HAT' has been renamed to 'HoeffdingAdaptiveTreeClassifier' in v0.5.0.
The old name will be removed in v0.7.0
 

Prequential Evaluation
Evaluating 1 target(s).
Pre-training on 10000 sample(s).
Evaluating...

Time limit reached (1000.00s). Evaluation stopped.
Processed samples: 510200
Mean performance:
HT - Accuracy     : 0.9831
HAT - Accuracy     : 0.8673


In [5]:
np.unique(models[0].predict(X),return_counts=True)

(array([0, 1]), array([5044, 4956]))

In [6]:
np.unique(models[1].predict(X),return_counts=True)

(array([0, 1]), array([5356, 4644]))

In [7]:
np.unique(y_weights,return_counts=True)

(array([0.4998, 0.5002]), array([4998, 5002]))